parameters:
    App\Api\Paypal\Reset\Tracking:
        sandbox: 0
        version: v1
        clientId: '%env(PAYPAL_CLIENTID)%'
        clientSecret: '%env(PAYPAL_CLIENTSECRET)%'
    App\Api\Oceanpayment\Tracking:
        account: '%env(OC_ACCOUNT)%'
        terminal: '%env(OC_TERMINAL)%'
        secureCode: '%env(OC_SECURECODE)%'

services:
    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - 'mysql:dbname=%env(DB_NAME)%; host=%env(DB_HOST)%; port=%env(DB_PORT)%'
            - { db_table: 'sessions', db_username: '%env(DB_USER)%', db_password: '%env(DB_PASS)%' }